=== micronaut-projects/micronaut-guides-sdk/guide-metadata.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "uri": "https://micronaut-projects.github.io/micronaut-guides-sdk/guide-metadata.schema.json",
  "type": "object",
  "required": ["title","intro","categories","publicationDate"],
  "properties": {
    "title": {
      "description": "The guide's title",
      "type": "string"
    },
    "projectName": {
      "description": "Root Project Name in Multi-module tutorials",
      "type": "string"
    },
    "authors": {
      "description": "The guide's authors",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "intro": {
      "description": "The guide introduction",
      "type": "string"
    },
    "publicationDate": {
      "description": "The guide publication date. It should follow the format YYYY-MM-DD",
      "type": "string",
      "format": "date",
      "pattern": "^\\d{4}\\-(0?[1-9]|1[012])\\-(0?[1-9]|[12][0-9]|3[01])$"
    },
    "minimumJavaVersion": {
      "description": "If the guide needs a minimum Java version, define it here",
      "type": "integer"
    },
    "maximumJavaVersion": {
      "description": "If the guide needs a maximum Java version, define it here",
      "type": "integer"
    },
    "cloud": {
      "description": "The acronym for the cloud service provider of the guide. For example, OCI for Oracle Cloud Infrastructure",
      "type": "string",
      "enum": ["OCI","AWS","GCP","Azure"]
    },
    "skipGradleTests": {
      "description": "Set it to true to skip running the tests for the Gradle applications for the guide",
      "type": "boolean"
    },
    "skipMavenTests": {
      "description": "Set it to true to skip running the tests for the Maven applications for the guide",
      "type": "boolean"
    },
    "asciidoctor": {
      "description": "The guide asciidoc file. If not specified, the guide slug followed by the .adoc suffix is used",
      "type": "string"
    },
    "languages": {
      "description": "The guide supported languages",
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["JAVA","GROOVY","KOTLIN"]
      }
    },
    "tags": {
      "description": "List of tags added to the guide. features are added automatically as tags. No need to repeat them here",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "buildTools": {
      "description": "By default the code in the guide is generated for Gradle and Maven. If a guide is specific only for a build tool, define it here",
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["MAVEN","GRADLE", "GRADLE_KOTLIN"]
      }
    },
    "testFramework": {
      "description": "The guide's test framework. By default Java and Kotlin applications are tested with JUnit5 and Groovy applications with Spock",
      "type": "string",
      "enum": ["SPOCK","JUNIT"]
    },
    "zipIncludes": {
      "description": "List of additional files with a relative path to include in the generated zip file for the guide",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "categories": {
      "description": "The guide's categories",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "slug": {
      "description": "The guide's slug. If not specified, the guides folder is used.",
      "type": "string"
    },
    "publish": {
      "description": "Whether the guide should be published, it defaults to true. You can set it to false for draft or base guides.",
      "type": "boolean"
    },
    "base": {
      "description": "Defaults to null; if set, indicates directory name of the base guide to copy before copying the current one",
      "type": "string"
    },
    "env": {
      "description": "The guide's environment variables",
      "type": "object"
    },
    "apps": {
      "description": "Applications created for the guide.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "description": "The app's name. For single application guides, the application needs to be named default. ",
            "type": "string"
          },
          "packageName": {
            "description": "The app's package name. It you don't specify, the package name example.micronaut is used",
            "type": "string"
          },
          "applicationType": {
            "description": "The app type.  It you don't specify, default is used",
            "type": "string",
            "enum": ["default","cli","function","grpc","messaging"]
          },
          "framework": {
            "description": "The app's framework. Default is Micronaut but Spring Boot is also supported",
            "type": "string"
          },
          "features": {
            "description": "The Micronaut Starter features' name that the app requires",
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "invisibleFeatures": {
            "description": "The app's invisible features",
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "kotlinFeatures": {
            "description": "The app's Kotlin features",
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "javaFeatures": {
            "description": "The app's Java features",
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "groovyFeatures": {
            "description": "The app's Groovy features",
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "validateLicense": {
            "type": "boolean"
          },
          "testFramework": {
            "description": "The app's test framework",
            "type": "string"
          },
          "excludeTest": {
            "description": "The tests that should not be run",
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "excludeSource": {
            "description": "The source files that should not be included",
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}

=== micronaut-projects/micronaut-guides-sdk/gdkexamples/guides/micronaut-data-jdbc-repository/metadata.json
{
  "title": "Create and Connect a Micronaut Application to a MySQL Database",
  "intro": "This guide describes how to create a database application using the Graal Development Kit for Micronaut (GDK). The application presents REST endpoints and stores data in a MySQL database using Micronaut® Data.",
  "authors": [
    "Sergio del Amo"
  ],
  "tags": [],
  "categories": [
    "Database"
  ],
  "languages": [
    "JAVA"
  ],
  "publicationDate": "2024-11-19",
  "zipIncludes": [
    "create_resources.sh",
    "settings.sh",
    "test_app.sh"
  ],
  "apps": [
    {
      "name": "default",
      "features": [
        "graalvm"
      ],
      "services": [
        "database"
      ]
    }
  ]
}

=== micronaut-projects/micronaut-guides-sdk/examples/guides/micronaut-hello-world/metadata.json
{
  "title": "Micronaut Hello World",
  "intro": "This guide shows you how to generate a Hello World endpoint in a Micronaut application.",
  "authors": ["Sergio del Amo"],
  "tags": [],
  "categories": ["Getting Started"],
  "languages": ["JAVA"],
  "publicationDate": "2024-11-19",
  "apps": [
    {
      "name": "default",
      "features": []
    }
  ]
}
